language: dart
dart:
  - stable
os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # you need this source to get the right version of libstdc++6
    packages:
      - libstdc++6
install:
    - git clone https://github.com/flutter/flutter.git -b stable
    - ./flutter/bin/flutter doctor # this is to avoid an error with pub in Travis
script:
    - ./flutter/bin/flutter run
cache:
  directories:
    - $HOME/.pub-cache
